In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:\\Users\\symev\\OneDrive\\Training\\Emeritus\\capstone project\\emeritus captone project\\Metro_Interstate_Traffic_Volume_Cleaned_FeatureEngineering.csv')

In [3]:
# Congestion category (data-driven quartiles of traffic_volume)
q1, q2, q3 = df["traffic_volume"].quantile([0.25, 0.5, 0.75]).values

def bucket(v):
    if v <= q1:
        return "Low"
    elif v <= q2:
        return "Medium"
    elif v <= q3:
        return "High"
    return "Severe"

df["congestion_category"] = df["traffic_volume"].apply(bucket)

In [4]:
# One-hot encode congestion category
congestion_encoded = pd.get_dummies(
    df["congestion_category"],
    prefix="congestion_category"
)

# Add the encoded columns back to the dataframe
df = pd.concat([df, congestion_encoded], axis=1)

In [5]:
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,hour,...,weather_Thunderstorm,weather_is_clear,weather_is_not_clear,temp_scaled,traffic_volume_scaled,congestion_category,congestion_category_High,congestion_category_Low,congestion_category_Medium,congestion_category_Severe
0,None,288.28,0.0,0.0,40,Clouds,Scattered Clouds,2012-10-02 09:00:00,5545,9,...,0,0,1,0.673215,0.761676,Severe,0,0,0,1
1,None,289.36,0.0,0.0,75,Clouds,Broken Clouds,2012-10-02 10:00:00,4516,10,...,0,0,1,0.689412,0.620330,High,1,0,0,0
2,None,289.58,0.0,0.0,90,Clouds,Overcast Clouds,2012-10-02 11:00:00,4767,11,...,0,0,1,0.692711,0.654808,High,1,0,0,0
3,None,290.13,0.0,0.0,90,Clouds,Overcast Clouds,2012-10-02 12:00:00,5026,12,...,0,0,1,0.700960,0.690385,Severe,0,0,0,1
4,None,291.14,0.0,0.0,75,Clouds,Broken Clouds,2012-10-02 13:00:00,4918,13,...,0,0,1,0.716107,0.675549,High,1,0,0,0

In [6]:
# Proxy accident-risk label
# High risk = severe/low-visibility weather conditions occurring
# together with High/Severe congestion.
# in "high_risk" column, 1 indicates high risk and 0 indicates no high risk

high_congestion = df["congestion_category"].isin(["High", "Severe"])

risky_weather = (
    df["weather_main"].isin(["Fog", "Haze", "Smoke","Thunderstorm", "Snow"]))


df["high_risk"] = (high_congestion & risky_weather).astype(int)

In [7]:
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,hour,...,weather_is_clear,weather_is_not_clear,temp_scaled,traffic_volume_scaled,congestion_category,congestion_category_High,congestion_category_Low,congestion_category_Medium,congestion_category_Severe,high_risk
0,None,288.28,0.0,0.0,40,Clouds,Scattered Clouds,2012-10-02 09:00:00,5545,9,...,0,1,0.673215,0.761676,Severe,0,0,0,1,0
1,None,289.36,0.0,0.0,75,Clouds,Broken Clouds,2012-10-02 10:00:00,4516,10,...,0,1,0.689412,0.620330,High,1,0,0,0,0
2,None,289.58,0.0,0.0,90,Clouds,Overcast Clouds,2012-10-02 11:00:00,4767,11,...,0,1,0.692711,0.654808,High,1,0,0,0,0
3,None,290.13,0.0,0.0,90,Clouds,Overcast Clouds,2012-10-02 12:00:00,5026,12,...,0,1,0.700960,0.690385,Severe,0,0,0,1,0
4,None,291.14,0.0,0.0,75,Clouds,Broken Clouds,2012-10-02 13:00:00,4918,13,...,0,1,0.716107,0.675549,High,1,0,0,0,0

In [8]:
 df.to_csv(r"C:\Users\symev\OneDrive\Training\Emeritus\capstone project\emeritus captone project\Metro_Interstate_Traffic_Volume_Cleaned_FeatureEngineering_wProxy.csv"
, index=False)